# Generated by Django 5.2.17 on 2026-10-03 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('code', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('league', 'Лига')], max_length=16, unique=True, verbose_name='код')),
                ('name', models.CharField(max_length=32, verbose_name='название')),
                ('tier', models.CharField(blank=True, help_text='Tier-00', max_length=16, verbose_name='метка уровня')),
                ('tagline', models.CharField(blank=True, max_length=160, verbose_name='подзаголовок')),
                ('cta', models.CharField(blank=True, max_length=48, verbose_name='текст кнопки')),
                ('recommended', models.BooleanField(default=False, verbose_name='рекомендуемый')),
                ('price_month', models.PositiveIntegerField(blank=True, null=True, verbose_name='цена за месяц, тыйын')),
                ('price_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='цена за год, тыйын')),
                ('currency', models.CharField(default='KGS', max_length=3, verbose_name='валюта')),
                ('limits', models.JSONField(blank=True, default=dict, help_text='{"active_tournaments": 3, "staff": 1, "formats": ["single"], "branding": false}; null — без лимита', verbose_name='лимиты и возможности')),
                ('features', models.JSONField(blank=True, default=list, verbose_name='пункты для страницы тарифов')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='порядок')),
            ],
            options={
                'verbose_name': 'тариф',
                'verbose_name_plural': 'тарифы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('status', models.CharField(choices=[('trialing', 'Пробный период'), ('active', 'Активна'), ('past_due', 'Просрочена'), ('canceled', 'Отменена'), ('expired', 'Истекла')], default='active', max_length=16, verbose_name='статус')),
                ('period', models.CharField(choices=[('month', 'Месяц'), ('year', 'Год')], default='month', max_length=8, verbose_name='период')),
                ('current_period_end', models.DateTimeField(blank=True, null=True, verbose_name='конец периода')),
                ('cancel_at', models.DateTimeField(blank=True, null=True, verbose_name='отмена с')),
                ('provider_id', models.CharField(blank=True, max_length=128, verbose_name='id у провайдера')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='orgs.organization', verbose_name='организация')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan', verbose_name='тариф')),
            ],
            options={
                'verbose_name': 'подписка',
                'verbose_name_plural': 'подписки',
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['trialing', 'active', 'past_due'])), fields=('organization',), name='subscription_one_live_per_org')],
            },
        ),
    ]
