# Generated by Django 5.2.17 on 2026-10-03 10:19

import apps.accounts.models
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='удалено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='почта')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='телефон')),
                ('nickname', models.CharField(max_length=24, verbose_name='ник')),
                ('full_name', models.CharField(blank=True, max_length=120, verbose_name='имя')),
                ('city', models.CharField(blank=True, max_length=64, verbose_name='город')),
                ('avatar', models.ImageField(blank=True, upload_to='users/avatars/', verbose_name='аватар')),
                ('banner', models.ImageField(blank=True, upload_to='users/banners/', verbose_name='баннер')),
                ('bio', models.TextField(blank=True, max_length=600, verbose_name='о себе')),
                ('main_role', models.CharField(blank=True, max_length=32, verbose_name='игровая роль')),
                ('default_role', models.CharField(choices=[('player', 'Игрок'), ('org', 'Организатор'), ('both', 'Игрок и организатор')], default='player', max_length=8, verbose_name='кабинет по умолчанию')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('ky', 'Кыргызча'), ('en', 'English')], default='ru', max_length=2, verbose_name='язык')),
                ('timezone', models.CharField(default='Asia/Bishkek', max_length=64, verbose_name='часовой пояс')),
                ('date_format', models.CharField(default='DD.MM.YYYY', max_length=16, verbose_name='формат даты')),
                ('looking_for_team', models.BooleanField(default=False, verbose_name='ищет команду')),
                ('email_verified', models.BooleanField(default=False, verbose_name='почта подтверждена')),
                ('phone_verified', models.BooleanField(default=False, verbose_name='телефон подтверждён')),
                ('is_active', models.BooleanField(default=True, help_text='Снимите, чтобы заблокировать вход', verbose_name='активен')),
                ('is_staff', models.BooleanField(default=False, verbose_name='суперадмин CTS')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='зарегистрирован')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
            },
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='GameAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('provider', models.CharField(choices=[('riot', 'Riot ID'), ('steam', 'Steam'), ('discord', 'Discord'), ('telegram', 'Telegram')], max_length=16)),
                ('external_id', models.CharField(max_length=128)),
                ('display_name', models.CharField(blank=True, max_length=128)),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'игровой аккаунт',
                'verbose_name_plural': 'игровые аккаунты',
            },
        ),
        migrations.CreateModel(
            name='LegalConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(max_length=16)),
                ('version', models.CharField(max_length=16)),
                ('accepted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'согласие',
                'verbose_name_plural': 'согласия',
            },
        ),
        migrations.CreateModel(
            name='PrivacySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_stats', models.BooleanField(default=True, verbose_name='показывать статистику')),
                ('show_city', models.BooleanField(default=True, verbose_name='показывать город')),
                ('invites_from_all', models.BooleanField(default=True, verbose_name='приглашения от всех')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'приватность',
                'verbose_name_plural': 'приватность',
            },
        ),
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitch', models.CharField(blank=True, max_length=200)),
                ('youtube', models.CharField(blank=True, max_length=200)),
                ('telegram', models.CharField(blank=True, max_length=200)),
                ('instagram', models.CharField(blank=True, max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'соцсети',
                'verbose_name_plural': 'соцсети',
            },
        ),
        migrations.CreateModel(
            name='UserGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'игра пользователя',
                'verbose_name_plural': 'игры пользователей',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('refresh_jti', models.CharField(db_index=True, max_length=64)),
                ('remember', models.BooleanField(default=True)),
                ('device', models.CharField(blank=True, max_length=64)),
                ('browser', models.CharField(blank=True, max_length=64)),
                ('os', models.CharField(blank=True, max_length=64)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'сессия',
                'verbose_name_plural': 'сессии',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Почта'), ('sms', 'SMS'), ('telegram', 'Telegram')], max_length=16)),
                ('purpose', models.CharField(choices=[('verify_email', 'Подтверждение почты'), ('change_email', 'Смена почты'), ('change_phone', 'Смена телефона'), ('two_factor', 'Вход с 2FA')], max_length=16)),
                ('target', models.CharField(help_text='Куда отправлен код', max_length=254, verbose_name='адрес')),
                ('code_hash', models.CharField(max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'код подтверждения',
                'verbose_name_plural': 'коды подтверждения',
            },
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='user_email_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nickname'), name='user_nickname_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='gameaccount',
            constraint=models.UniqueConstraint(fields=('provider', 'external_id'), name='game_account_external_unique'),
        ),
        migrations.AddConstraint(
            model_name='gameaccount',
            constraint=models.UniqueConstraint(fields=('user', 'provider'), name='game_account_one_per_provider'),
        ),
        migrations.AddConstraint(
            model_name='usergame',
            constraint=models.UniqueConstraint(fields=('user', 'game'), name='user_game_unique'),
        ),
        migrations.AddIndex(
            model_name='verificationcode',
            index=models.Index(fields=['user', 'purpose', '-created_at'], name='accounts_ve_user_id_f57e3f_idx'),
        ),
    ]
