# Generated by Django 5.2.17 on 2026-10-04 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_format',
        ),
        migrations.RemoveField(
            model_name='user',
            name='timezone',
        ),
        migrations.DeleteModel(
            name='UserGame',
        ),
    ]
