# Generated by Django 5.2.17 on 2026-10-03 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('name', models.CharField(max_length=64, verbose_name='название')),
                ('slug', models.SlugField(max_length=32, unique=True, verbose_name='slug')),
                ('short', models.CharField(help_text='Для логотипа-заглушки: VL, CS', max_length=4, verbose_name='сокращение')),
                ('publisher', models.CharField(blank=True, max_length=64, verbose_name='издатель')),
                ('team_size', models.PositiveSmallIntegerField(default=5, verbose_name='игроков в основе')),
                ('max_subs', models.PositiveSmallIntegerField(default=2, verbose_name='максимум запасных')),
                ('account_provider', models.CharField(choices=[('riot', 'Riot ID'), ('steam', 'Steam'), ('discord', 'Discord'), ('telegram', 'Telegram'), ('manual', 'Вручную')], default='manual', max_length=16, verbose_name='проверка аккаунта')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('beta', 'Бета'), ('off', 'Выключена')], db_index=True, default='active', max_length=8, verbose_name='статус')),
                ('art', models.ImageField(blank=True, upload_to='games/', verbose_name='арт')),
                ('maps', models.JSONField(blank=True, default=list, verbose_name='карты')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='порядок')),
            ],
            options={
                'verbose_name': 'игра',
                'verbose_name_plural': 'игры',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BracketFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('code', models.CharField(choices=[('single', 'Single Elimination'), ('double', 'Double Elimination'), ('groups', 'Группы + плей-офф'), ('swiss', 'Швейцарская система'), ('league', 'Круговая лига')], max_length=16, unique=True, verbose_name='код')),
                ('name', models.CharField(max_length=64, verbose_name='название')),
                ('enabled', models.BooleanField(default=True, verbose_name='включён')),
                ('is_beta', models.BooleanField(default=False, verbose_name='бета')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='порядок')),
                ('games', models.ManyToManyField(blank=True, related_name='formats', to='games.game', verbose_name='игры')),
            ],
            options={
                'verbose_name': 'формат сетки',
                'verbose_name_plural': 'форматы сетки',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RulesTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('title', models.CharField(max_length=128, verbose_name='название')),
                ('body', models.JSONField(default=list, help_text='[{"title": "1. Общие положения", "body": "…"}]', verbose_name='разделы')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='версия')),
                ('is_current', models.BooleanField(default=True, verbose_name='текущая')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules_templates', to='games.game', verbose_name='игра')),
            ],
            options={
                'verbose_name': 'шаблон регламента',
                'verbose_name_plural': 'шаблоны регламентов',
                'ordering': ['game', '-version'],
                'constraints': [models.UniqueConstraint(fields=('game', 'version'), name='rules_template_game_version'), models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('game',), name='rules_template_one_current')],
            },
        ),
    ]
