# Generated by Django 5.2.17 on 2026-10-03 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='удалено')),
                ('name', models.CharField(max_length=80, verbose_name='название')),
                ('slug', models.SlugField(max_length=48, unique=True, verbose_name='slug')),
                ('logo', models.ImageField(blank=True, upload_to='orgs/logos/', verbose_name='логотип')),
                ('accent_color', models.CharField(default='#8A9BB4', max_length=7, verbose_name='акцентный цвет')),
                ('show_sponsors', models.BooleanField(default=False, verbose_name='показывать спонсоров')),
                ('custom_domain', models.CharField(blank=True, max_length=253, verbose_name='свой домен')),
                ('verification_status', models.CharField(choices=[('none', 'Не проверена'), ('pending', 'На проверке'), ('verified', 'Проверена'), ('rejected', 'Отклонена')], default='none', max_length=16, verbose_name='верификация')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_orgs', to=settings.AUTH_USER_MODEL, verbose_name='владелец')),
            ],
            options={
                'verbose_name': 'организация',
                'verbose_name_plural': 'организации',
            },
        ),
        migrations.CreateModel(
            name='OrgMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('role', models.CharField(choices=[('owner', 'Владелец'), ('admin', 'Админ'), ('judge', 'Судья'), ('moderator', 'Модератор')], max_length=16, verbose_name='роль')),
                ('last_active', models.DateTimeField(blank=True, null=True, verbose_name='последняя активность')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='orgs.organization', verbose_name='организация')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_memberships', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'сотрудник организации',
                'verbose_name_plural': 'сотрудники организаций',
                'constraints': [models.UniqueConstraint(fields=('organization', 'user'), name='org_member_unique')],
            },
        ),
    ]
