# Generated by Django 5.2.17 on 2026-10-04 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='accent_color',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='custom_domain',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='show_sponsors',
        ),
    ]
