/** Ключи TanStack Query — одно место, чтобы сокет и мутации обновляли тот же кэш. */
export const qk = {
  games: ["games"] as const,
  plans: ["plans"] as const,
  tournaments: (f: object) => ["tournaments", f] as const,
  tournament: (slug: string) => ["tournament", slug] as const,
  bracket: (slug: string) => ["bracket", slug] as const,
  tournamentSchedule: (slug: string) => ["tournament-schedule", slug] as const,
  match: (slug: string, code: string) => ["match", slug, code] as const,
  matchStats: (slug: string, code: string) => ["match-stats", slug, code] as const,
  schedule: (date: string, tournament?: string) => ["schedule", date, tournament ?? "all"] as const,
  notifications: (kind = "all") => ["me", "notifications", kind] as const,
  invites: ["me", "invites"] as const,
  myMatches: ["me", "matches"] as const,
  myTournaments: ["me", "tournaments"] as const,
  myProfile: ["me", "profile"] as const,
  myTeam: ["me", "team"] as const,
  orgDashboard: ["org", "dashboard"] as const,
  orgTournaments: (tab: string) => ["org", "tournaments", tab] as const,
  orgTournament: (id: string) => ["org", "tournament", id] as const,
  applications: (id: string) => ["org", "applications", id] as const,
  orgMatches: (id: string) => ["org", "matches", id] as const,
  dispute: (id: string, code: string) => ["org", "dispute", id, code] as const,
  slots: (id: string, day: number) => ["org", "slots", id, day] as const,
  checkin: (id: string) => ["org", "checkin", id] as const,
  participants: (q: object) => ["org", "participants", q] as const,
  mailings: ["org", "mailings"] as const,
  analytics: (p: string) => ["org", "analytics", p] as const,
  staff: ["org", "staff"] as const,
  adminUsers: (q: object) => ["control", "users", q] as const,
  moderation: ["control", "moderation"] as const,
  payments: ["control", "payments"] as const,
  adminNews: ["control", "news"] as const,
};
